import "./globals.css";
import RegisterModal from "@/components/modals/RegisterModal";
import LoginModal from "@/components/modals/LoginModal";
import {
  JosephineSans,
  LuckiestGuy,
  RubikMonoOne,
  inter,
  openSans,
  playfairDisplay,
} from "@/fonts";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Toaster } from "sonner";
import { BackgroundImage } from "@/components/background-image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={`overflow-x-hidden font-inter bg-gray-50 ${JosephineSans.variable} ${inter.variable} ${openSans.variable} ${RubikMonoOne.variable} ${playfairDisplay.variable} ${LuckiestGuy.variable}`}
        >
          {/* <ModalProvider /> */}
          <RegisterModal />
          <LoginModal />
          <Toaster />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
